### ISSUE TITLE
_Ready order is wrong

### ISSUE THREAD

**Issue by BenDBrown** [BenDBrown/MayGameJam#61]
the _Ready method on FuelTank is called after the _Ready method on PlayerShip which causes the data on fuel tank to not be set when FuelManager is trying to access it. This is fixed with a bandaid solution at the moment where FuelManager directly accesses the resource on FuelTank.

relevant lines:
- FuelManager, Line: 42
- FuelTank, Line: 11
- Ship, Line: 35

**Comment by GenelleGeerman** [comment]
Can you push the changes since I don't see them on dev @BenDBrown

**Comment by BenDBrown** [comment]
fixed

**Comment by GenelleGeerman** [comment]
#62
